wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1704723675.439564
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      - 105
      2:
      - 1
      - 41
      - 50
      - 55
      - 105
      3:
      - 7
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
