wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1704691283.360136
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 105
      2:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 105
      3:
      - 7
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_score
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: val_score
      5: 1
      6:
      - 1
