model:
  _target_: zebanas.spaces.model.Network
  # _partial_: true
  chromos: null
  network_channels: [32, 16, 24, 40, 80, 112, 192, 360]
  strides: [1, 2, 2, 2, 1, 2, 1]
  dropout: 0.2
  num_classes: 10
  last_channels: 1440
  width_mult: 1.0
  depth_mult: 1.0  

chromosome:
  _target_: zebanas.genetic.chromosome.Chromosome
  bound:
    lower: [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    upper: [6, 6, 6, 6, 6, 6, 6, 11, 11, 1, 1, 1]
    expand_choice: [1, 2, 4, 6]

algorithm:
  _target_: zebanas.algorithms.brute_force.BruteForce
  pop_size: 1000

  sampler:
    _target_: zebanas.genetic.samplers.BruteForcePart0Part2Sampler
    bound:
      lower: [1, 0, 0, 0, 0, 0]
      upper: [6, 11, 11, 1, 1, 1]

  evaluator:
    _target_: zebanas.evaluators.score_latency.ScoreAndLatencyEvaluator
    score_evaluator:
      _target_: zebanas.evaluators.zico.ZicoProxy
      loss_fn:
        _target_: zebanas.criterions.cross_entropy.CrossEntropyCriterion
    
    latency_evaluator:
      _target_: zebanas.evaluators.latency.CellLatencyEstimator

  survivor:
    _target_: zebanas.genetic.survivors.ParetoFrontSurvivor

searcher:
  _target_: zebanas.tasks.search.CellbyCellSearcher
  n_cells: 7
  select_func: null
  backward: true

data:
  _target_: zebanas.data.vision.cifar10.DataLoaderforSearchGetter
  data_dir: "/home/haitt/workspaces/data/vision/cifar10"
  batch_size: 64
  n_batches: 2

execute:
  device: 'cuda'
  start_step: 1
  end_step: 2
  sols_dir: "logs/2023-12-04/checkpoints"
  save_interval: 5