model:
  _target_: zebanas.spaces.model.Network
  # _partial_: true
  chromos: null
  network_channels: [32, 16, 24, 40, 80, 112, 192, 360]
  strides: [1, 2, 2, 2, 1, 2, 1]
  dropout: 0.2
  num_classes: 10
  last_channels: 1440
  width_mult: 1.0
  depth_mult: 1.0  

chromosome:
  _target_: zebanas.genetic.chromosome.Chromosome
  bound:
    lower: [1, 1, 1, 1, 1, 1, 1, 3, 1, 0, 0, 0]
    upper: [6, 6, 6, 6, 6, 6, 6, 11, 11, 0, 1, 0]
    expand_choice: [1, 2, 4, 6]

algorithm:
  _target_: zebanas.algorithms.pla.PruningLatencyAware
  pop_size: 100
  latency_bound:
    upper: [0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4]
    lower: [0.59, 0.89, 1.19, 1.49, 1.79, 2.09, 2.39]

  sampler:
    _target_: zebanas.genetic.samplers.FullCellSampler
    bound:
      lower: [1, 3, 1, 0, 0, 0]
      upper: [6, 11, 11, 0, 1, 0]
    expand_choice: ${chromosome.bound.expand_choice}

  score_evaluator:
    _target_: zebanas.evaluators.zico.ZicoProxy
    repetitions: 30
    loss_fn:
      _target_: zebanas.criterions.cross_entropy.CrossEntropyCriterion
  
  latency_evaluator:
    _target_: zebanas.evaluators.latency.CellLatencyEstimator
    path: "zebanas/evaluators/latency_table.pth"

  survivor:
    _target_: zebanas.genetic.survivors.ParetoFrontSurvivor
    alpha: 0.5

searcher:
  _target_: zebanas.tasks.search.CellbyCellSearcher
  n_cells: 7
  select_func: null
  backward: false

data:
  _target_: zebanas.data.vision.cifar10.DataLoaderforSearchGetter
  data_dir: "/home/haitt/workspaces/data/vision/cifar10"
  batch_size: 2
  n_batches: 2

execute:
  device: 'cuda'
  start_step: 0
  end_step: 7
  sols_dir: "logs/2023-12-08"
  save_interval: 5