callback:
  checkpoint: 
    monitor: "val_score"
    dirpath: "zebanas/checkpoints/cifar10"
    filename: "cifar10-{epoch:03d}-{val_score:.4f}"
    auto_insert_metric_name: true
    mode: "max"
    save_top_k: 3
    save_last: true

logger_name: "gecco2024"

trainer:
  accelerator: "gpu"
  devices: [0]
  max_epochs: 162
  val_check_interval: 200
  num_sanity_val_steps: 2
  gradient_clip_val: 5.
  log_every_n_steps: 1
  deterministic: true

module:
  _target_: zebanas.tasks.classification.NetworkModule
  model:
    _target_: zebanas.spaces.model.Gecco2024Network
    # _partial_: true
    chromos:
    - [6, 6, 4, 4, 4, 3, 3, 3]
    - [6, 6, 4, 6, 4, 4, 4, 3]
    - [3, 6, 3, 3, 6, 3, 3, 3]
    - [6, 5, 3, 3, 3, 3, 3, 3]
    - [5, 6, 4, 4, 4, 3, 6, 3]
    network_channels: [16, 24, 48, 80, 128, 192]
    strides: [1, 1, 2, 1, 2, 1]
    dropout: 0.1
    num_classes: 10
    last_channels: 1280
  loss_fn:
    _target_: zebanas.criterions.MultitaskLossFunction
    num_classes: 10
  
  metric_fn:
    _target_: zebanas.metrics.classifcation.Accuracy
  
data:
  _target_: zebanas.data.vision.cifar10.CIFAR10LightningModule
  data_dir: "/home/haitt/workspaces/data/vision/cifar10"
  batch_size: 64
  image_size: 32
  crop_size: 32

api_path: "/home/haitt/workspaces/codes/nas-bench/NATS-Bench/api/NATS-tss-v1_0-3ffb9-simple"